#!/bin/bash -e

SPHINX_DOC_ROOT=${SPHINX_DOC_ROOT:=/sphinx}
SPHINX_BUILDER=${SPHINX_BUILDER:=html}
SPHINX_OUT_DIR=${SPHINX_OUT_DIR:=_build}

cd ${SPHINX_DOC_ROOT}

if [[ -e ${REQUIREMENTS_FILE} ]]; then
  pip install -r ${REQUIREMENTS_FILE}
fi

sphinx-build -b ${SPHINX_BUILDER} . ${SPHINX_OUT_DIR}
if [[ ${SPHINX_BUILDER} == "pdf" ]]; then
  cd ${SPHINX_OUT_DIR} && make all-pdf
elif [[ ${SPHINX_BUILDER} == "pdfja" ]]; then
  cd ${SPHINX_OUT_DIR} && make all-pdf-ja
fi
